### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by raphaelshirley** [ICRAR/libprofit#1]
Hello,

I am trying to run the usage.py example script that comes with the pyprofit code. I am getting the following error

error: axrat > 1, must have axrat <= 1

Is scipy allowing the parameter to veer outside its allowed range or is there some problem with my code. I am very keen to use Gaussians in line with the advice of Hogg and Lang 2012. It currently doesn't seem as if you include gaussian profiles. How might I add this to the C++ library? Would it be possible to define the psf analytically in order to take advantage of convolution speed up associated with mixtures of gaussians?

I am just starting to try and use pyprofit instead of my clunky Galfit wrapper which necessitates writing feedme files and then reading fits output files which is less that ideal.

Many thanks,

Raphael Shirley
Astronomy Centre
University of Sussex, UK

**Comment by rtobar** [comment]
Hi Raphael,

The first issue seems related more to pyprofit than to libprofit per se, so in principle I think it should have been reported there. In any case, I re-run the latest usage.py script with the latest pyprofit code and it run through the end. In the lists defining the initial conditions the axrat values are modeled to range between log10(-1) = 0.1 and log10(0) = 1, so they should be within boundaries. Have you changed these values at all? Otherwise I'm a bit surprised that you're getting this error. If it persists please send me all the relevant information, including the version of the software you're using (hopefully the git commit associated to it, or the version you downloaded from pypi if installed via pip), the contents of the usage.py script, the version of scipy, etc.

Regarding the analytics psf definition, the R ProFit package exposes this support. Internally it makes a first call to libprofit to calculate the psf from its analytical description, and then a second call to actually evaluate the profiles and perform convolution with the resulting psf. Is that a suitable option? If so you could imitate the same behaviour in python, which we could include in pyprofit as well.

**Comment by raphaelshirley** [comment]
Ah yes sorry it is related to pyprofit. I will try to update everything and run it again to see if that fixes the problem.

I will look into implementing the R method in Python. 

One of the main things I am working on is evaluating the Bayesian evidence for different models (e.g. Sersic only vs Bulge/Disk or One Sersic vs Two Sersic at two locations. One of the approximate solutions to the integral over parameter space requires the Hessian matrix at the chi squared minima. I presume I would have to write some code to numerically evaluate the Hessian at a given point in parameter space but wondered if you have done anything similar such that I shouldn't waste time rewriting code?

Anyway, thank you very much for your informative reply. I'm under the impression you are developing Bayesian methods for investigating galaxy profile models and thought it wouldn't do any harm to keep you informed about what I am working on.

Best,

Raphael.

**Comment by rtobar** [comment]
Hi Raphael,

The C++ code in libprofit contains purely the imaging side of things -- i.e., it is only concerned with creating an image from a given number of profile definitions, an optional PSF, etc; any statistics happening on top of this is not part of libprofit.

Having said that, the R ProFit package in https://github.com/ICRAR/ProFit not only wraps libprofit to provide imaging, but also provides ample functionality on statistics and optimization. https://github.com/ICRAR/pyprofit is a simpler wrapper to expose libprofit under python, but as you know it also contains a simple optimization example as well. I would suggest you take a look to the R code to get an idea of what it can do regarding bayesian statistics, and to have a read at [Profit's paper](https://arxiv.org/abs/1611.08586) which should give a good explanation of how things are organized and what is available in the different packages.
